### ISSUE TITLE
[FEAT] Support of Row Grouping

### ISSUE THREAD

**Issue by totalard** [shlomiassaf/ngrid#90] opened 2020-04-12 08:52 UTC
#### Please describe the feature you would like to request.
It would be better if you include row grouping, .

You can see a perfect exmple at demo.odoo.com.

Once grouped, the column that used to group will be hidden

#### What is the use-case or motivation for this proposal?
Row grouping is mandatory for tabular data analysus

#### Is there anything else we should know?

just check demo.odoo.com. choose any apps, and findout how the grouping implemented

**Comment by shlomiassaf** [comment] 2020-04-21 20:58
I agree, this is an important feature.

I consider these feature as "peripheral" features which are not directly related to the grid but more to it's eco system, it's definitely not internal to the grid.

The thing that makes this one different is that it changes the structure of the grid from the root.
When grouping is applied the entire layout change and each group now shows a new grid instance with a panel like UI that wraps it.

This require some thinking because the grid itself is UI agnostic, it does not favour any style so how do I implement that while allowing new styles added?

I will work on this one in the future, any thoughts, suggestions and PRs that follows are much appreciated.

Thanks

**Comment by shlomiassaf** [comment] 2020-10-13 09:18
Duplicate of #60

**Closed by shlomiassaf** 2020-10-13 09:18 UTC
Labels: comp: core, comp: core-plugins, type: RFC / discussion / question, type: feature
