### ISSUE TITLE
The virtual scrolling with a pagination feature

### ISSUE THREAD

**Issue by dmitry-bas** [shlomiassaf/ngrid#98] opened 2020-05-25 14:44 UTC
The virtual scrolling with a pagination feature should be used to display large amounts of records without paging. When scrolling with the vertical scrollbar, the component executes HTTP requests to load and refresh the existing records. The overall behavior is smooth and with no flicker.

**Comment by shlomiassaf** [comment] 2020-07-14 20:54
Hi,

I don't understand.

Are you talking about **infinite scroll**?

**Comment by shlomiassaf** [comment] 2020-07-14 22:34
@dmitry-bas  see https://github.com/shlomiassaf/ngrid/issues/96#issuecomment-658444768

**Comment by dmitry-bas** [comment] 2020-07-15 05:48
Yes. For example: https://www.ag-grid.com/javascript-grid-infinite-scrolling/

**Comment by shlomiassaf** [comment] 2020-07-15 18:52
Ok, @dmitry-bas @davidglezz So look this is a duplicate of #96 

I gave a very simple example on how this can be done now, without any extension....

But I will work on a solid extension to make it easier to use.

I challenge here is making it easier to use, cause as you can see in the demo it's not that difficult right now.

**Closed** 2020-07-16 06:15 UTC
Labels: question, type: feature
